name: catkinlint
method: http://ppa.launchpad.net/roehling/latest/ubuntu
suites: [trusty, xenial, artful, bionic]
component: main
architectures: [i386, amd64, armhf, arm64, source]
filter_formula: Source (== catkin-lint)
