name: catkinlint
method: http://ppa.launchpad.net/roehling/latest/ubuntu
suites: [precise, trusty, utopic, vivid, wily, xenial, yakkety, zesty]
component: main
architectures: [i386, amd64, source]
filter_formula: Source (== catkin-lint)
