name: ffmpeg-debian-backports
method: http://ftp.us.debian.org/debian/
#http://httpredir.debian.org/debian
suites: [jessie]
source_suite: jessie-backports
component: main
architectures: [amd64, arm64, armel, armhf, i386, source]
filter_formula: Package (% *ffmpeg* ) | Package (== ffmpeg)
