name: opennippa
method: http://ppa.launchpad.net/v-launchpad-jochen-sprickerhof-de/pcl/ubuntu
suites: [lucid, oneiric, precise, quantal]
component: main
architectures: [i386, amd64, source, armel]
filter_formula: Package (% openni* )
