name: trollius
method: http://ppa.launchpad.net/wjwwood/trollius-backports/ubuntu
suites: [trusty]
component: main
architectures: [amd64, armel, armhf, arm64, i386, source]
filter_formula: Package (== python-trollius) | Package (== python3-trollius)
