name: vtk-backports
method: http://archive.ubuntu.com/ubuntu/
suites: [xenial]
source_suite: yakkety
component: universe>main
architectures: [amd64, i386, source]
filter_formula: Package (% libvtk6* ) | Package (% vtk6* )
